openapi: 3.0.0
servers:
  - url: http://localhost:8080
info:
  version: latest
  title: PROG3 - TD2
paths:
  /players:
    get:
      tags:
        - Players
      summary: Get all players
      operationId: getPlayers
      responses:
        '200':
          description: List of Players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      tags:
        - Players
      summary: Add new players
      operationId: addPlayers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePlayer'
      responses:
        '200':
          description: The created players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
    put:
      tags:
        - Players
      summary: Update existing players
      operationId: updatePlayers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: The updated players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
  /matches:
    get:
      tags:
        - Matches
      summary: Get all matches
      operationId: getMatches
      responses:
        '200':
          description: List of Matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /matches/{id}:
    get:
      tags:
        - Matches
      summary: Get Match by specified id
      parameters:
        - name: matchId
          in: path
          schema:
            type: integer
          required: true
      operationId: getMatchById
      responses:
        '200':
          description: The match with specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
  /matches/{matchId}/goals:
    post:
      tags:
        - Matches
      summary: Add some goals to a match
      parameters:
        - name: matchId
          in: path
          schema:
            type: integer
          required: true
      description: Be careful! A guardian player can not score a goal.
      operationId: addGoals
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Scorer'
      responses:
        '200':
          description: The updated match with new scores
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CreatePlayer:
      type: object
      properties:
        name:
          type: string
        isGuardian:
          type: boolean
        teamName:
          type: string
    Player:
      allOf:
        - $ref: '#/components/schemas/CreatePlayer'
      properties:
        id:
          type: integer
    Match:
      type: object
      properties:
        id:
          type: integer
        datetime:
          type: string
          format: datetime
        stadium:
          type: string
        teamA:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
        teamB:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
    PlayedTeam:
      type: object
      properties:
        team:
          $ref: '#/components/schemas/Team'
        goals:
          type: integer
        scorers:
          type: array
          items:
            $ref: '#/components/schemas/Scorer'
    Scorer:
      type: object
      properties:
        player:
          $ref: '#/components/schemas/Player'
        isOG:
          type: boolean
        scoreTime:
          type: integer
